### ISSUE TITLE
NoClassDefFoundError error in Android 4.4 not Android 5.0

### ISSUE THREAD

**Issue by y-rok** [jyoungrok/ShareCam_Android#3]
It doesn't matter in android 5.4 but there is problem in Android 4.4
When i start application, app is killed with below logs

```
06-06 00:50:24.198  30588-30588/com.claude.sharecam:aviary_cds E/dalvikvm﹕ Could not find class 'com.aviary.android.feather.sdk.internal.cds.AviaryCdsDefaultContentLoader', referenced from method com.aviary.android.feather.sdk.internal.cds.CdsDatabaseHelper.onOpen
06-06 00:50:24.218  30588-30588/com.claude.sharecam:aviary_cds E/dalvikvm﹕ Could not find class 'com.amazonaws.services.s3.AmazonS3Client', referenced from method com.claude.sharecam.api.AWS.init
06-06 00:50:24.218  30588-30588/com.claude.sharecam:aviary_cds E/dalvikvm﹕ Could not find class 'com.claude.sharecam.api.AWS$2', referenced from method com.claude.sharecam.api.AWS.uploadProfileImage
06-06 00:50:24.228  30588-30588/com.claude.sharecam:aviary_cds E/dalvikvm﹕ Could not find class 'com.claude.sharecam.api.MyCookieManager', referenced from method com.claude.sharecam.api.ApiManager.<init>
06-06 00:50:24.228     903-1727/? E/ActivityManagerServiceEx﹕ ** ERROR: PROCESS CRASHED
06-06 00:50:24.228  30588-30588/com.claude.sharecam:aviary_cds E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.claude.sharecam:aviary_cds, PID: 30588
    java.lang.NoClassDefFoundError: com.claude.sharecam.api.MyCookieManager
            at com.claude.sharecam.api.ApiManager.<init>(ApiManager.java:43)
            at com.claude.sharecam.api.ApiManager.newInstance(ApiManager.java:36)
            at com.claude.sharecam.Util.onCreate(Util.java:90)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4415)
            at android.app.ActivityThread.access$1500(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by y-rok** [comment]
It seems like this problem is occured by adding libraries..
I should look thorugh dependencies in build.gradle and find which dependencies make problem
I will make new project and run several times with different depencies list

**Comment by y-rok** [comment]
When i remove **compile 'com.google.android.gms:play-services:7.3.0'** and **compile 'org.parceler:parceler:0.2.13'**, the application does work properly.
I don't know why these depencies made problem and i should find the reason when i want to add these dependencies

my final dependencies is the below

```
 compile 'com.parse.bolts:bolts-android:1.+'
    compile 'com.android.support:recyclerview-v7:22.1.1'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
    compile 'com.facebook.android:facebook-android-sdk:4.0.0'
    compile 'com.adobe.creativesdk:image:4.0.0'
    compile 'com.adobe.creativesdk.foundation:auth:0.3.94'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile files('libs/aws-android-sdk-core-2.1.10.jar')
    compile files('libs/aws-android-sdk-s3-2.1.10.jar')
    compile files('libs/image-chooser-library-1.3.1.jar')
    compile files('libs/gson-2.2.4.jar')
    compile files('libs/aws-android-sdk-mobilenalytics-2.1.10.jar')
    compile files('libs/libphonenumber-7.0.5.jar')
    compile files('libs/Parse-1.9.2.jar')
    compile files('libs/ParseFacebookUtilsV4-1.9.2.jar')
    compile files('libs/picasso-2.5.2.jar')
    compile files('libs/retrofit-1.9.0.jar')
```
